# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Perchema
email: aleks.trc@gmail.com
description: > 
  Alexander "Perchema" Crustev's website. A place where you can find 
  information about his projects and things he finds interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://judgesystem.tk" # the base hostname & protocol for your site
github_username:  Alaxe

# Build settings
markdown: kramdown
